name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: python -m pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Check code formatting with Black
        run: poetry run black --check .

      - name: Lint code with flake8
        run: poetry run flake8 .

      # Optional: Check import sorting
      - name: Check import sorting with isort
        run: poetry run isort --check-only .

      - name: Run tests with pytest
        run: poetry run pytest