name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - run: python -m pip install poetry

      - run: poetry install

      # Format code using Black
      - run: poetry run black .

      # Lint code using flake8
      - run: poetry run flake8 .

      # Run tests using pytest
      - run: poetry run pytest
